sources:
  - name: "PadCare Labs - Website"
    url: "https://padcarelabs.com/"
  - name: "PadCare LinkedIn"
    url: "https://www.linkedin.com/company/padcare/"
  - name: "Forbes India - PadCare Labs"
    url: "https://www.forbesindia.com/article/startups/padcare-labs-solving-sanitary-napkins-disposal-conundrum-one-binfull-at-a-time/83365/1"
  - name: "World Economic Forum - PadCare"
    url: "https://www.weforum.org/videos/this-indian-start-up-converts-used-sanitary-pads-into-hygienic-pulp-and-plastic/"
  - name: "Pune International Centre - PadCare"
    url: "https://puneinternationalcentre.org/padcare-labs-the-green-and-easy-way-to-managing-menstrual-hygiene/"
  - name: "Dassault Systèmes press release - PadCare"
    url: "https://www.3ds.com/newsroom/press-releases/india/dassault-systemes-enables-padcare-labs-design-and-develop-worlds-first-smokeless-sanitary-pad-disposal-and-recycling-system"